### ISSUE TITLE
antivirus detection for old loader

### ISSUE THREAD

**Issue by ask2018** [C0dingschmuser/SRU_Internal#1]
Hello. Nice trainer. But just for info - the old loader is detected as virus recently by Eset Endpoint AV. I suppose it is false detection, but still not good. New loader is not detected.

﻿Log
Scan Log
Version of detection engine: 27121 (20230424)
Date: 24.4.2023  Time: 12:55:23
Scanned disks, folders and files: C:\...\Download\OldLoader.zip
C:\...\Download\OldLoader.zip » ZIP » OldLoader/SRU_Internal_Loader.exe - a variant of Win32/GenKryptik_AGen.YG trojan - deleted
Number of scanned objects: 2
Number of detections: 1
Number of cleaned objects: 1
Time of completion: 12:55:39  Total scanning time: 16 sec (00:00:16)

Notes:
[1] Object has been deleted as it only contained the virus body.

**Comment by C0dingschmuser** [comment]
Yeah it's a false positive. Unfortunately that's quite common with trainers/cheats since they directly manipulate/access process memory which some antiviruses see as malicious (although it is not). That's also the reason i created the new loader since it uses some clever tricks which enables it to run on game launch without the user having to manually start an executable
